### PR TITLE
feat: pass is verified from notify config object to subs metadata

### PR DESCRIPTION
**Pull request by enesozturk**
# Changes

On the w3i app, we filter the projects with the app domain and get the verification status to do conditional rendering for unapproved/dev mode projects. This will help us get rid of extra logic on the UI. Added `isVerified` field to `metadata` of the subscription object.

### CODE REVIEW

**Comment by bkrem** [comment]
Nice 🙌  makes sense to me conceptually but will defer to @devceline & @chris13524 given that there may be other caveats here if we make this a first class citizen of the subscription object + this isn't technically part of the agreed spec atm I believe

**Comment by devceline** [comment]
> Nice 🙌 makes sense to me conceptually but will defer to @devceline & @chris13524 given that there may be other caveats here if we make this a first class citizen of the subscription object + this isn't technically part of the agreed spec atm I believe: https://specs.walletconnect.com/2.0/specs/clients/notify/notify-config

I'm not too big on this change, [Slack thread](https://walletconnect.slack.com/archives/C044SKFKELR/p1704274198380929?thread_ts=1704274000.423619&cid=C044SKFKELR). I just don't like the precedent this sets for the SDK. If we want to add something to the `Metadata` object we should update the specs and agree team-wide

**Comment by bkrem** [comment]
Just saw the Slack thread; agreed that it should be a coordinated change to the metadata object if really wanted/needed 👍

**Comment by devceline** [comment]
Closing as it is not the concern of notify client, but of the using app

**Pull request closed without merging**
